apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment-numeric
  labels:
    version: numeric
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app-numeric
  template:
    metadata:
      labels:
        app: flask-app-numeric
    spec:
      containers:
        - name: flask-app
          image: anhaid/flask-app:anhaid/flask-app:new
          ports:
            - containerPort: 8080