apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app-green
  template:
    metadata:
      labels:
        app: flask-app-green
    spec:
      containers:
        - name: flask-app
          image: anhaid/flask-app:${{ github.event.client_payload.image }}  # Dynamically updated image tag
          ports:
            - containerPort: 8080
