apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app-${{ github.event.client_payload.version }}  # Dynamically set version
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
