apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app-blue  # Initially points to Blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer