apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app-green  # Switch between flask-app-green or flask-app-blue for traffic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
