name: CD Workflow

on:
  repository_dispatch:
    types:
      - deploy-new-version

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Authenticate with Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Install gke-gcloud-auth-plugin
      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      # Set up kubectl
      - name: Set up kubectl
        run: gcloud container clusters get-credentials flask-cluster --zone us-central1-a --project ${{ secrets.GCP_PROJECT_ID }}

      # Deploy the new version (Blue)
      - name: Deploy New Version (Blue)
        run: |
          kubectl set image deployment/flask-deployment-blue flask-app=${{ github.event.client_payload.image }}
          kubectl rollout status deployment flask-deployment-blue

      # Switch traffic to Blue (manual approval step)
      - name: Approve Traffic Switch
        uses: hmarr/auto-approve-action@v2
        with:
          approved-by: ${{ secrets.APPROVER }}

      - name: Switch Traffic to Blue
        run: |
          kubectl patch svc flask-service -p '{"spec":{"selector":{"app":"flask-app-blue"}}}'

      # Optionally, scale down Green
      - name: Scale Down Green Deployment
        run: |
          kubectl scale deployment flask-deployment-green --replicas=0

      # Promote Blue to Green
      - name: Promote Blue to Green
        run: |
          kubectl set image deployment/flask-deployment-green flask-app=${{ github.event.client_payload.image }}
          kubectl rollout status deployment flask-deployment-green
          
      # Update Kubernetes resource definitions in the GitHub repository
      - name: Update K8S Resource Definitions
        run: |
          # Update the resource definitions with the new image tag (if necessary)
          sed -i 's|image: anhaid/flask-app:.*|image: anhaid/flask-app:${{ github.event.client_payload.image }}|' k8s/flask-deployment-green.yaml
          sed -i 's|image: anhaid/flask-app:.*|image: anhaid/flask-app:${{ github.event.client_payload.image }}|' k8s/flask-deployment-blue.yaml
          
          # Commit and push the changes to GitHub
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add k8s/flask-deployment-green.yaml k8s/flask-deployment-blue.yaml
          git commit -m "Update Kubernetes resources with new image"
          git push origin main
