name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run unit tests
      - name: Run unit tests
        run: |
          export PYTHONPATH=$(pwd)  # Add the current directory to the Python path
          pytest tests/

      # Build Docker image for new version
      - name: Build Docker image
        run: |
          docker build -t anhaid/flask-app:new .

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push Docker image for new version
      - name: Push Docker image
        run: |
          docker push anhaid/flask-app:new

      # Trigger CD workflow with new image tag
      - name: Trigger CD
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: flask-app-cicd  # Ensure this is the correct repository
          event-type: deploy-new-version
          client-payload: '{"image": "anhaid/flask-app:${{ github.sha }}"}'
