name: CI Workflow

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment and install dependencies
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      # Step 3: Run tests (using pytest for this example)
      - name: Run Tests
        run: |
          pytest tests/

      # Step 4: Log in to Docker Hub and build/push Docker image
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t anhaid/flask-app:${{ github.sha }} .
          docker push anhaid/flask-app:${{ github.sha }}
